depends_on("python/3.6.1")
depends_on("py-numpy/1.14.3_py36")
depends_on("py-scipy/1.1.0_py36")
depends_on("py-pandas/0.23.0_py36")
depends_on("py-pillow/5.1.0_py36")
depends_on("py-matplotlib/2.1.2_py36")
prepend_path("PATH","/home/groups/trc/python/bin")
prepend_path("PYTHONPATH","/home/groups/trc/python/lib/python3.6/site-packages")
whatis("Name:        antspy")
whatis("Version:     0.2.2")
whatis("Category:    math, biology")
whatis("URL:         https://github.com/ClandininLab/modules")
whatis("Description: python bindings for ANTs")
